TYPE=VIEW
query=select `wlsp`.`wlact`.`id` AS `id`,`wlsp`.`wlact`.`event` AS `event`,`wlsp`.`wlact`.`mac` AS `mac`,`wlsp`.`wlact`.`firstseen` AS `firstseen`,`wlsp`.`wlact`.`lastseen` AS `lastseen`,`wlsp`.`wlact`.`rectime` AS `rectime`,`wlsp`.`wlact`.`subevent` AS `subevent`,`wlsp`.`wlact`.`oldvalue` AS `oldvalue`,`wlsp`.`wlact`.`newvalue` AS `newvalue`,`wlsp`.`wlact`.`stat` AS `stat`,`wlsp`.`wlact`.`action` AS `action` from `wlsp`.`wlact` order by `wlsp`.`wlact`.`id` desc limit 150
md5=756113c71d73464df491b6bb8ff1907a
updatable=0
algorithm=0
definer_user=root
definer_host=%
suid=1
with_check_option=0
timestamp=2014-11-11 13:35:18
create-version=1
source=select `wlact`.`id` AS `id`,`wlact`.`event` AS `event`,`wlact`.`mac` AS `mac`,`wlact`.`firstseen` AS `firstseen`,`wlact`.`lastseen` AS `lastseen`,`wlact`.`rectime` AS `rectime`,`wlact`.`subevent` AS `subevent`,`wlact`.`oldvalue` AS `oldvalue`,`wlact`.`newvalue` AS `newvalue`,`wlact`.`stat` AS `stat`,`wlact`.`action` AS `action` from `wlact` order by `wlact`.`id` desc limit 150
client_cs_name=latin1
connection_cl_name=latin1_swedish_ci
view_body_utf8=select `wlsp`.`wlact`.`id` AS `id`,`wlsp`.`wlact`.`event` AS `event`,`wlsp`.`wlact`.`mac` AS `mac`,`wlsp`.`wlact`.`firstseen` AS `firstseen`,`wlsp`.`wlact`.`lastseen` AS `lastseen`,`wlsp`.`wlact`.`rectime` AS `rectime`,`wlsp`.`wlact`.`subevent` AS `subevent`,`wlsp`.`wlact`.`oldvalue` AS `oldvalue`,`wlsp`.`wlact`.`newvalue` AS `newvalue`,`wlsp`.`wlact`.`stat` AS `stat`,`wlsp`.`wlact`.`action` AS `action` from `wlsp`.`wlact` order by `wlsp`.`wlact`.`id` desc limit 150
